export const LOADING_MESSAGES = [
  "Assembling Avengers...",
  "Awkward silence...",
  "Becoming a walrus...",
  "Blowing on the cartridge...",
  "Booting up Sega Genesis...",
  "Browsing Netflix...",
  "Checking audio levels...",
  "Dancing in the dark...",
  "Debating about superhero movies...",
  "Deploying carrier pigeons...",
  "Dreaming of sushi...",
  "Gaining consciousness...",
  "Grabbing another beer...",
  "Having Skype issues...",
  "Importing games...",
  "Inserting LaserDisc...",
  "Leaving rails...",
  "Mentioning Star Wars...",
  "Predicting Oscar winners...",
  "Reading a book...",
  "Rewatching The Shining...",
  "Scrambling to pick topics...",
  "Snoring...",
  "Turning it off and on again...",
  "Typing at 200wpm...",
];

export const LOADING_RECOMMENDATIONS = [
  "Formulating recommendations...",
  "Gathering recommendations...",
  "Loading recommendations...",
  ...LOADING_MESSAGES,
];

export const PLACEHOLDER_EXAMPLES = [
  "1975",
  "2000 film",
  "2007",
  "2008 book",
  "2015",
  "ben 2017 series",
  "bread game",
  "comic",
  "film 2000",
  "film festival",
  "last broadcast",
  "meat train",
  "michael 2016",
  "mister mosquito",
  "superfight",
  "the lobster",
  "typing of the dead",
  "Barry Lyndon",
  "Book",
  "Comic",
  "Dane book",
  "Danganronpa",
  "Film",
  "Game",
  "Grabbers film",
  "Josh Wierschke",
  "Series",
  "Song of the Sea",
  "Tokyo game",
  "Trollhunter",
  "Tyler Film 2016",
];

// localStorage key
export const THEME = "theme";
